### ISSUE TITLE
source map 활용

### ISSUE THREAD

**Issue by sangwook-kim** [studye/react#2]
`webpack.config.js`에 보면 `devtool: "source-map"` 설정이 있는데요,

이 map 파일은 어디에 생기고 개발자 도구에서 어떻게 사용하는 것인가요?

소스맵을 써 본적이 없어서 질문드립니다.

근데 왜 나는 Label - question 적용이 안되지;;;

**Comment by denzels** [comment]
target 파일하고 같은 위치에 생길거예요.

개발자도구 설정에 Enable JavaScript source maps 옵션을 켜두시면 됩니다.
![screenshot 2016-03-10 23 30 28](https://cloud.githubusercontent.com/assets/304682/13672464/44e69288-e718-11e5-849c-4e1150d3897f.png)

**Comment by sangwook-kim** [comment]
음 어제 활용해봤는데, 
일단 소스 창에 보이는 방식은 아니고 
`debugger;` 지시자를 쓰거나 오류가 발생하면 원래 소스가 보이더군.

그냥 소스 패널에서 열려서 보이고 클릭해서 브레이크 포인트 추가할 수 있을 줄 알았는데 그건 아니네. 

여튼 땡스요.

**Comment by denzelsN** [comment]
Sources 탭에 보면 좌하단에 "{}" 이 있는데 이거 누르면 sourcemap 먹인 소스가 나와요.
거기서 브레이크 포인트를~~

![2016-03-17 2 28 16](https://cloud.githubusercontent.com/assets/11496446/13837244/85334bea-ec4c-11e5-98a7-8935b5a6114d.png)
